export const REQUEST_TOP5HOT = "REQUEST_TOP5HOT";
export type REQUEST_TOP5HOT = typeof REQUEST_TOP5HOT;

export const REQUEST_CITYDATA = "REQUEST_CITYDATA";
export type REQUEST_CITYDATA = typeof REQUEST_CITYDATA;

export const REQUEST_TOP5CHANGE = "REQUEST_TOP5CHANGE";
export type REQUEST_TOP5CHANGE = typeof REQUEST_TOP5CHANGE;

export const REQUEST_CHANGE_BASIC_STATIC = "REQUEST_CHANGE_BASIC_STATIC";
export type REQUEST_CHANGE_BASIC_STATIC = typeof REQUEST_CHANGE_BASIC_STATIC;

export const REQUEST_CHANGE_PERCENT = "REQUEST_CHANGE_PERCENT";
export type REQUEST_CHANGE_PERCENT = typeof REQUEST_CHANGE_PERCENT;

export const REQUEST_CHANGE_RANK = "REQUEST_CHANGE_RANK";
export type REQUEST_CHANGE_RANK = typeof REQUEST_CHANGE_RANK;
